name: setup repo

on:
  create:
  workflow_dispatch:

jobs:
  setup:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Git
        run: |
          git config --global user.name "Mayank Chaudhari<https://mayank-chaudhari.vercel.app>"
          git config --global user.email "mayank.srmu@gmail.com"
          git fetch
          git checkout main
      - name: Set up repo
        run: |
          git rm .tkb
          mv ./scripts/.tkb ./.tkb
          rm -rf ./docs
      - name: Push changes back to repo
        run: |
          git add .
          git commit -m 'Craete rebrand config 💖 <a href="https://mayank-chaudhari.vercel.app" target="_blank">Mayank Kumar Chaudhari</a> [skip ci]'
          git push origin main
